#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

if [ -z "${VCT_RSYNC_URL}" ]; then
    echo "VCT_RSYNC_URL not defined"
    exit 1
fi

/usr/bin/rsync -a --delete-after ${VCT_RSYNC_URL} /vct/
chown -R root:root /vct
cd /vct/ansible
/usr/bin/python2.7 -u /usr/local/bin/ansible-playbook -c local $1
