#!/usr/bin/env python2.7
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import argparse
import os
import sys

HERE = os.path.abspath(os.path.dirname(__file__))

sys.path.insert(0, os.path.join(HERE, 'testing'))

from vcttesting.environment import (
    create_docs,
    create_global,
    create_hgdev,
)


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(title='environment', dest='environment')

    sp = subparsers.add_parser('docs',
                               help='Generate documentation')

    sp = subparsers.add_parser('hgdev',
                               help='Mercurial hooks and extensions')

    sp = subparsers.add_parser('test',
                               help='Mercurial extensions and server environment')

    args = parser.parse_args()

    env = args.environment

    if env == 'docs':
        info = create_docs()
    elif env == 'hgdev':
        info = create_hgdev()
    elif env in 'test':
        info = create_global()
    else:
        raise Exception('unhandled environment: %s' % env)

    print('%s environment created successfully.' % env)
    print('')
    print('To activate this environment, source a shell script:')
    print('')
    print('  $ source %s' % os.path.relpath(info['activate'], HERE))
    print('')
    print('To update the environment, just run this command again.')
    print('')
    print('To run tests relevant to this environment:')
    print('')
    print('  $ ./run-tests')


if __name__ == '__main__':
    main()
