#!/usr/bin/env bash
# Bail on any setup error
set -eu

ROOT=`pwd`
VENV=${ROOT}/venv
PYTHON_VERSION=python3

if [ ! -d ${VENV}/lib ]; then
  python3 -m venv ${VENV}
fi

cd ${ROOT}

# activate fails on read of PS1, which doesn't exist in non-interactive shell
set +u
source ${VENV}/bin/activate
set -u

# Install `wheel` so `python setup.py bdist_wheel` works.
pip install wheel

# Note: pycrypto may not build on OSX with hombrew gmp unless you add:
# export CFLAGS='-I/usr/local/include -L/usr/local/lib'
pip install --upgrade --require-hashes -r deploy-requirements.txt

cd testing
python setup.py develop
cd ..
