#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import sys

HERE = os.path.abspath(os.path.dirname(__file__))

def main(args):
    activate = os.path.join(HERE, 'venv', 'bin', 'activate_this.py')
    execfile(activate, dict(__file__=activate))
    sys.executable = os.path.join(HERE, 'venv', 'bin', 'python')

    sys.path.insert(0, os.path.join(HERE, 'testing'))

    from mach.main import Mach

    m = Mach(os.getcwd())

    m.define_category('mozreview', 'MozReview',
        'Mozilla Code Review Service', 50)
    import vcttesting.mozreview_mach_commands

    return m.run(args)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
