#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import sys

HERE = os.path.abspath(os.path.dirname(__file__))


def main(args):
    if "VIRTUAL_ENV" not in os.environ:
        print(
            "WARNING: no VIRTUAL_ENV detected."
            + " You may want to run this in a Python 3.9 virtualenv."
            + " Continuing anyway ..."
        )

    from mach.main import Mach

    m = Mach(os.getcwd())

    m.define_category(
        "pulse", "Pulse", "Control and Interact with the Pulse Message Broker", 50
    )
    import vcttesting.pulse_mach_commands

    return m.run(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
