#!/bin/sh

die() {
    echo "$1" 1>&2
    exit ${2:1}
}

if [ -z "$REPO_ROOT" ]; then
    REPO_ROOT=http://hg/
fi

if [ -z "$REPO_TARGET" ]; then
    REPO_TARGET=/repo/hg/mozilla
fi

if [ -n "$SSH_ORIGINAL_COMMAND" ]; then
    # We're running under ssh; the repository is given in the third field
    repo=`echo $SSH_ORIGINAL_COMMAND | cut -d ' ' -f 3`
else
    repo="$1"
fi

repo=`echo "$repo" | sed 's#[^\._-/[:alnum:]]##g'`
test -z "$repo" && die "need a repo to clone, relative to /repo/hg/mozilla" 

GLOBAL_HG_OPTS="--config hooks.pretxnchangegroup.z_linearhistory= --config hooks.pretxnchangegroup.z_loghistory="

name=`echo $repo | sed 's#^/*##'`
src=${REPO_ROOT}/$name

cd $REPO_TARGET || die "$REPO_TARGET does not exist, cannot create repositories there"

if [ -d "$name" ]; then
    echo "$name already exists, pulling"
    cd $name
    hg pull $GLOBAL_HG_OPTS 
elif [ \! -e $name ]; then
    mkdir -p `dirname $name` 
    echo "$name does not yet exist, cloning"
    hg clone $GLOBAL_HG_OPTS -U -v "$src" $name
else
    die "WTF is $REPO_TARGET/$name"
fi


# Local variables:
# mode: shell-script
# tab-width: 4
# indent-tabs-mode: nil
# end:
