#!/usr/bin/env python

import cgi
import cgitb
import sys
import re
import subprocess

#cgitb.enable()
cgitb.enable(display=0)


def check_repo_name(repo_name):
    good_chars = re.compile('^(\w|-|/|\.\w)+\s*$')
    if not good_chars.search(repo_name):
        sys.stderr.write('Only alpha-numeric characters, ".", and "-" are '
                         'allowed in the repository names.\n')
        sys.stderr.write('Please try again with only those characters.\n')
        sys.exit(1)
    return True

print "Content-Type: text/plain"
print

form = cgi.FieldStorage()
#if not form or not form.has_key("repo"):
if not form or "repo" not in form:
    print "Need a repository to check"
    sys.exit(1)

repo = form.getfirst("repo", "")
if not check_repo_name(repo):
    print "You've included some illegal characters in your repo name"
    sys.stderr.write("Warning: illegal characters in repo name\n")
    sys.exit(1)
# ensure that the repo is within repo_root
if repo.find('/../') != -1:
    print "That's not allowed"
    sys.stderr.write("Warning: /../ found in a repo name.\n")
    sys.exit(1)

command = ('/usr/bin/ssh -o StrictHostKeyChecking=no -o '
           'UserKnownHostsFile=/dev/null -l vcs-sync@mozilla.com '
           '-i /etc/mercurial/mirror hg.mozilla.org '
           'repo-group %s' % repo)
proc = subprocess.Popen(command,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        shell=True)
(out, err) = proc.communicate()
print out

# Local variables:
# mode: python
# indent-tabs-mode: nil
# tab-width: 4
# end:
