#!/usr/bin/env python2.7
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2 or any later version.

from __future__ import print_function

import sys

if __name__ == '__main__':
    print('MozReview has been shut off and the `git-mozreview` executable '
          'should no longer be used')
    sys.exit(1)
