#!/usr/bin/python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from __future__ import print_function

import os
import socket
import sys

if 'BROKER_ID' not in os.environ:
    print('error: BROKER_ID not in environment', file=sys.stderr)
    sys.exit(1)

broker_id = os.environ['BROKER_ID']
server_properties = '/etc/kafka/server.properties'
zoo_cfg = '/etc/zookeeper/zoo.cfg'

advertise_host = socket.gethostbyaddr(socket.gethostname())[2][0]
advertise_port = '9092'
hostnames = ('hgssh', 'hgweb0', 'hgweb1')
servers = [
    '%s:2888:3888' % s
    for s in hostnames
]

# Tell ZooKeeper what the servers are.
lines = []
with open(zoo_cfg, 'r') as fh:
    for line in fh:
        if not line.startswith('server.'):
            lines.append(line.rstrip())

for i, server in enumerate(servers):
    line = 'server.%d=%s' % (i, server)
    lines.append(line)
lines.append('')

with open(zoo_cfg, 'w') as fh:
    fh.write('\n'.join(lines))

print('wrote zookeeper server list')

# Set the ZooKeeper current server ID.
with open('/var/lib/zookeeper/myid', 'w') as fh:
    fh.write(broker_id)

print('wrote zookeeper id')

# Set the Kafka broker ID and ZooKeeper server list.
lines = []
with open(server_properties, 'r') as fh:
    for line in fh:
        if line.startswith('advertised.host.name='):
            continue
        if line.startswith('advertised.port='):
            continue
        if line.startswith('broker.id='):
            continue
        if line.startswith('zookeeper.connect='):
            continue

        lines.append(line.rstrip())

lines.append('broker.id=' + broker_id)
lines.append('advertised.host.name=' + advertise_host)
lines.append('advertised.port=' + advertise_port)

hostports = ['%s:2181/hgmoreplication' % h for h in hostnames]
connect = ','.join(hostports)
lines.append('zookeeper.connect=' + connect)
lines.append('')

with open(server_properties, 'w') as fh:
    fh.write('\n'.join(lines))

print('wrote kafka server.properties')
