#!/usr/bin/python -u
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import sys

with open('/kafka-servers.tmp', 'w') as fh:
    fh.write('\n'.join(sys.argv[1:]))

# Do file move so write is atomic. Otherwise clients may see inconsistent
# data.
os.rename('/kafka-servers.tmp', '/kafka-servers')
