#!/usr/bin/env bash

set -e

mkdir -p ${VENV}

VIRTUALENV_VERSION=16.1.0

# Securely download virtualenv, setuptools, and pip.
${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/virtualenv-${VIRTUALENV_VERSION}.tar.gz \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}.tar.gz \
    f899fafcd92e1150f40c8215328be38ff24b519cd95357fa6e78e006c7638208 && \
  cd ${VENV} && tar -xzf virtualenv-${VIRTUALENV_VERSION}.tar.gz && \
  rm -f ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/setuptools-* \
        ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/pip-*

${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/appdirs-1.4.3-py2.py3-none-any.whl \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/appdirs-1.4.3-py2.py3-none-any.whl \
    d8b24664561d0d34ddfaec54636d502d7cea6e29c3eaf68f3df6180863e2166e

${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/packaging-18.0-py2.py3-none-any.whl \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/packaging-18.0-py2.py3-none-any.whl \
    f95a1e147590f204328170981833854229bb2912ac3d5f89e2a8ccd2834800c9

${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/pip-18.1-py2.py3-none-any.whl \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/pip-18.1-py2.py3-none-any.whl \
    7909d0a0932e88ea53a7014dfd14522ffef91a464daaaf5c573343852ef98550

${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/pyparsing-2.3.0-py2.py3-none-any.whl \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/pyparsing-2.3.0-py2.py3-none-any.whl \
    40856e74d4987de5d01761a22d1621ae1c7f8774585acae358aa5c5936c6c90b

${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/setuptools-40.5.0-py2.py3-none-any.whl \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/setuptools-40.5.0-py2.py3-none-any.whl \
    e329a5c458c6acb5edc2b5c4ad44280c053ba827dc82fd5e84a83e22bb05460d

${ROOT}/scripts/download-verify https://s3-us-west-2.amazonaws.com/moz-packages/six-1.11.0-py2.py3-none-any.whl \
    ${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv_support/six-1.11.0-py2.py3-none-any.whl \
    832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb

${VENV}/virtualenv-${VIRTUALENV_VERSION}/src/virtualenv.py --no-download --python=python2.7 ${VENV}

# The wheelhouse is shared between VENVs
mkdir -p ${ROOT}/venv/wheelhouse
