FROM ubuntu:18.04

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    gcc \
    gettext \
    git \
    libcurl4-openssl-dev \
    libffi-dev \
    liblzma-dev \
    libsasl2-dev \
    libldap2-dev \
    libssl-dev \
    npm \
    mercurial \
    python3 \
    python-dev \
    sqlite3 \
    zlib1g-dev && \
  apt-get clean -y && rm -rf /var/lib/apt/lists

RUN hg clone https://hg.mozilla.org/hgcustom/version-control-tools /vct-cache && \
  cd /vct-cache && \
  NO_DOCKER=1 ./create-test-environment

VOLUME /work
