Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu-1404-amd64'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.network 'forwarded_port', guest: 80, host: 12000
  config.vm.network 'forwarded_port', guest: 8001, host: 12001
  config.vm.synced_folder '../../', '/version-control-tools'

  config.vm.provision :shell, path: '../puppet/vagrant-bootstrap.sh'
  config.vm.provision :shell,
    inline: 'puppet apply --verbose --modulepath=/var/puppet-modules/modules /version-control-tools/testing/puppet/manifests/unifiedserver.pp'
end
