#!/bin/bash

cd /repos
hg clone http://hgrb/$1 inbound-$1
hg clone http://hgrb/$1
cd /repos/$1

cat > .hg/hgrc << EOF
[ui]
username = Otto Land <autoland@example.com>

[extensions]
purge =
rebase =
rewritecommitdescriptions = /home/ubuntu/version-control-tools/autoland/hgext/rewritecommitdescriptions.py
strip =

[paths]
upstream = /repos/inbound-$1
$1 = http://hgrb/$1
mozreview-push = ssh://hgrb/$1
try = /repos/try
inbound = /repos/inbound-$1
EOF
