$provision = <<SCRIPT

# Give VM some swap.
if [ ! -e /var/swap ]; then
  dd if=/dev/zero of=/var/swap bs=1048576 count=512
  mkswap /var/swap
fi
swapon /var/swap

apt-get -y remove chef puppet python-pip python-virtualenv && apt-get -y autoremove
# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
# sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
apt-get update
apt-get -y dist-upgrade
# apt-get -y install btrfs-tools

# if [ ! -e /var/btrfs ]; then
#   dd if=/dev/zero of=/var/btrfs bs=1048576 count=12000
#   mkfs.btrfs /var/btrfs
# fi

# if [ ! -d /var/lib/docker ]; then
#   mkdir /var/lib/docker
# fi

# mount /var/btrfs /var/lib/docker

# Docker may have been started before btrfs was mounted. If so, it would
# have started in devicemapper mode. Force a restart to pick up btrfs.
# restart docker

apt-get -y install git libbz2-dev libffi-dev libldap2-dev libncurses5-dev libreadline-dev libsasl2-dev libsqlite3-0 libsqlite3-dev libssl-dev libxslt1-dev python-dev sqlite3 tcl-dev unzip zlib1g-dev
# usermod --append -G docker vagrant
SCRIPT

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu1404amd64'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.synced_folder '../../', '/version-control-tools'
  config.vm.provision "shell", inline: $provision
end
