$provision = <<SCRIPT
apt-get update
apt-get -y upgrade
apt-get -y install mercurial python-dev python-virtualenv
SCRIPT

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu1404amd64'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.synced_folder '../../', '/version-control-tools'
  config.vm.provision "shell", inline: $provision
end
