- name: check if virtualenv exists
  stat:
    path: "{{ venv }}"
  register: venv_exists

- name: check if virtualenv has the right python
  stat:
    path: "{{ venv }}/bin/{{ python | basename }}"
  register: venv_python

- name: delete virtualenv
  file:
    path: "{{ venv }}"
    state: absent
  when: venv_exists.stat.exists and not venv_python.stat.exists

- name: create Python 3 virtualenv in {{ venv }}
  command: "{{ python }} -m venv {{ venv }} creates={{ venv }}/bin/{{ python | basename }}"

- name: copy requirements.txt for {{ venv }}
  copy: src={{ requirements }}
        dest={{ venv }}/requirements.txt
        mode=0644

- name: populate virtualenv {{ venv }}
  command: "{{ venv }}/bin/pip install --require-hashes -r {{ venv }}/requirements.txt"
