---
- name: install supervisor config
  copy: src=supervisor-{{ item }}.conf
        dest=/etc/supervisor.d/{{ item }}.conf
        owner=root
        group=root
        mode=0644
  with_items:
    - docker
    - test-kafkabroker

# Hack up rsyslog config so it works without systemd
- name: remove systemd from rsyslog
  replace:
    path: /etc/rsyslog.conf
    regexp: 'module\(load="imjournal"[^)]*\)'
    replace: ''

- name: enable local syslog logging
  replace:
    dest: /etc/rsyslog.conf
    regexp: 'SysSock.Use="off"'
    replace: 'SysSock.Use="on"'

- name: install Docker support files
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - enable-fastannotate
    - entrypoint.py
    - set-config-option
    - set-mirror-key.py

- name: Install IP address documents for prioritizing streamed clone bundles
  copy: src={{ item }} dest=/var/hg/{{ item }} owner=hg group=hg mode=0644
  with_items:
    - moz-ip-ranges.txt
    - aws-ip-ranges.json
    - gcp-ip-ranges.json
    - test_instance_data.json

- name: set moz-ip-path for tests
  ini_file:
    dest: /etc/mercurial/hgrc
    section: hgmo
    option: mozippath
    value: /var/hg/moz-ip-ranges.txt

- name: install test ssh config for hg user
  copy:
    src: ssh_config
    dest: /home/hg/.ssh/config
    owner: hg
    group: hg

- name: trust hgrc files owned by root
  ini_file:
    dest: /etc/mercurial/hgrc
    section: trusted
    option: users
    value: hg, root
