#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

REPO=$1
GROUP=$2

for arg in "$@"
do
    case $arg in
        --non-publishing)
        NONPUBLISHING=1
        ;;
        *)
        ;;
    esac
done

/var/hg/venv_tools/bin/hg init /repo/hg/mozilla/${REPO}
chown -R hg:${GROUP} /repo/hg/mozilla/${REPO}
find /repo/hg/mozilla/${REPO} | xargs chmod g+w
find /repo/hg/mozilla/${REPO} -type d | xargs chmod g+s

if [ -n "${NONPUBLISHING}" ]; then
  echo "marking repo as non-publishing"
  cat >> /repo/hg/mozilla/${REPO}/.hg/hgrc << EOF
[phases]
publish = False
EOF
fi
