#!/var/hg/venv_testing/bin/python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Runs a simple HTTP server that records POSTed SNS subscription data
# to a local file so tests can read it and verify content.

import json
import sys

from http.server import (
    BaseHTTPRequestHandler,
    HTTPServer,
)
from urllib.parse import parse_qs


class RequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        cl = int(self.headers['content-length'])
        body = self.rfile.read(cl)

        data = parse_qs(body)

        with open('/sns-messages', 'a') as fh:
            fh.write('POST %s ' % self.path.encode('utf-8'))
            data = json.dumps(
                data, 
                indent=4,
                separators=(',', ': '),
                sort_keys=True,
            )
            fh.write(data)
            fh.write('\n')

        self.send_response(200)
        self.end_headers()


httpd = HTTPServer(('', int(sys.argv[1])), RequestHandler)
httpd.serve_forever()
