#!/var/hg/venv_testing/bin/python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Runs a simple HTTP server that records POSTed SNS subscription data
# to a local file so tests can read it and verify content.

# TRACKING py3
try:
    from http.server import (
        BaseHTTPRequestHandler,
        HTTPServer,
    )
    from cgi import parse_qs
except ImportError:
    from BaseHTTPServer import (
        BaseHTTPRequestHandler,
        HTTPServer,
    )
    from urlparse import parse_qs

import json
import sys


class RequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        cl = int(self.headers['content-length'])
        body = self.rfile.read(cl)

        data = parse_qs(body)

        with open('/sns-messages', 'ab') as fh:
            fh.write(b'POST %s ' % self.path.encode('utf-8'))
            fh.write(json.dumps(data, indent=4, sort_keys=True,
                                separators=(',', ': ')))
            fh.write(b'\n')

        self.send_response(200)
        self.end_headers()


httpd = HTTPServer(('', int(sys.argv[1])), RequestHandler)
httpd.serve_forever()
