#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

# Extension complains if repoid is not set.
# This is arguably a bug in the extension.
hg --config extensions.rbserver=! init /repo/hg/mozilla/$1

cat > /repo/hg/mozilla/$1/.hg/hgrc << EOF
[reviewboard]
repoid = $2
EOF

chown -R hg:scm_level_1 /repo/hg/mozilla/$1
find /repo/hg/mozilla/$1 | xargs chmod g+w
find /repo/hg/mozilla/$1 -type d | xargs chmod g+s
