#!/usr/bin/env python2
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This script downloads a URL to the local path specified and verifies
# the hash of the file before saving it to disk.

import hashlib
import io
import sys
import urllib2

url, path, expected_hash = sys.argv[1:]

fh = urllib2.urlopen(url)
data = io.BytesIO(fh.read())

# For now we assume the hash is SHA-256. We could support prefixing
# the hash if we need to support other hashes.

hasher = hashlib.sha256()
hasher.update(data.getvalue())

if hasher.hexdigest() != expected_hash:
    print('hash verification failed: expected %s; got %s' % (
          expected_hash, hasher.hexdigest()))
    sys.exit(1)

with open(path, 'wb') as fh:
    fh.write(data.getvalue())

print('wrote %d bytes to %s' % (len(data.getvalue()), path))
sys.exit(0)
