#!/usr/bin/env python2
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# A script that executes its arguments as a new process and only
# prints its output if the executed command exited non-zero.

import subprocess
import sys

p = subprocess.Popen(sys.argv[1:], stdout=subprocess.PIPE,
                     stderr=subprocess.STDOUT)
out, err = p.communicate()
ret = p.poll()
if ret:
    print(out)
    sys.exit(ret)

sys.exit(0)
