---
- name: install packages required to use LDAP for system auth
  yum: name={{ item }} state=present
  with_items:
    - nss-pam-ldapd
    - openldap-clients
    - openssh-server

- name: install packages required to use LDAP for system auth (centos7)
  yum: name=authconfig
       state=present
  when: ansible_distribution_major_version == '7'

- name: install packages required to use LDAP for system auth (rocky8+)
  yum: name=authselect
       state=present
  when: ansible_distribution_major_version | int >= 8

- name: create directory for LDAP certificates
  file: path=/etc/openldap/cacerts
        state=directory
        owner=root
        group=root
        mode=0755

- name: install Mozilla certificates
  copy: src={{ item.src }}
        dest=/etc/openldap/cacerts/{{ item.dest }}
        owner=root
        group=root
        mode=0644
  with_items:
    - { src: files/mozilla-root-ca.crt, dest: mozilla.crt }
    - { src: files/mozilla-root-certificate-services.crt, dest: ca.crt }

- name: check if nslcd profile exists
  stat:
    path: /etc/authselect/custom/nslcd/README
  register: nslcd_exists

- name: create authselect nslcd profile
  command: authselect create-profile --base-on=minimal --symlink-pam --symlink-meta --symlink-dconf nslcd
  when: ansible_distribution_major_version | int >= 8 and not nslcd_exists.stat.exists

- name: create nsswitch.conf template
  copy:
    src: files/nsswitch.conf-ldap
    dest: /etc/authselect/custom/nslcd/nsswitch.conf
  when: ansible_distribution_major_version | int >= 8

- name: configure system authentication settings
  template: src=nslcd.conf.j2
            dest=/etc/nslcd.conf
  tags: docker-startup

- name: configure openldap client
  template: src=ldap.conf.j2
            dest=/etc/openldap/ldap.conf
  tags: docker-startup
  when: ansible_distribution_major_version | int >= 8

- name: run authconfig
  command: /usr/sbin/authconfig --enablemkhomedir --enableldap --enableldapauth --ldapserver={{ ldap_uri }} {{ ldap_starttls | ternary('--enableldapstarttls', '') }} --ldapbasedn={{ basedn }} --updateall
  tags: docker-startup
  when: ansible_distribution_major_version == '7'

- name: run authselect
  command: authselect select custom/nslcd --force
  tags: docker-startup
  when: ansible_distribution_major_version | int >= 8

- name: ensure nslcd service enabled and running (server only)
  service: name=nslcd.service
           enabled=yes
           state=started
  when: is_testing is not defined

- name: configure sshd
  copy: src=sshd_config
        dest=/etc/ssh/sshd_config
  notify: restart sshd
  tags: docker-startup

- name: generate SSH host keys (Docker only)
  command: /usr/bin/ssh-keygen -A -N ''
  when: is_testing is defined
