#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

# We don't preserve owner/group here because chown is slow on certain
# Docker filesystems, like overlay2.
/usr/bin/rsync -rlpt --delete-after /vct-mount/ /vct/
cd /vct/ansible
/usr/bin/python -u /usr/bin/ansible-playbook -c local $1
