---
- name: install supervisor config
  copy: src=supervisor-docker.conf
        dest=/etc/supervisor.d/docker.conf
        owner=root
        group=root
        mode=0644

# Docker doesn't have full TTYs. sudo will fail unless we remove the
# requirement that a TTY be present.
- name: Remove SSH TTY requirement
  replace: dest=/etc/sudoers regexp='^Defaults    requiretty.*$' replace=''

# Docker isn't running systemd. Remove the rsyslog config file telling
# rsyslog to bind to /run/systemd/journal/syslog so it binds to /dev/log
# by default and logging tools work.
- name: remove systemd syslog config
  file: path=/etc/rsyslog.d/listen.conf
        state=absent

# Hack up rsyslog config so it works without systemd
- name: remove systemd from rsyslog
  replace: dest=/etc/rsyslog.conf
           regexp='^\$ModLoad imjournal.*'
           replace=''

- name: enable local syslog logging
  replace: dest=/etc/rsyslog.conf
           regexp='^\$OmitLocalLogging on'
           replace='$OmitLocalLogging off'

- name: disable syslog journal file
  replace: dest=/etc/rsyslog.conf
           regexp='^\$IMJournalStateFile'
           replace='#$IMJournalStateFile'

- name: install support scripts
  copy: src={{ item }} dest=/{{ item }} mode=0755
  with_items:
    - configure-events-servers
    - create-repo
    - set-hgrc-option
    - set-ldap-property
    - set-mirrors.py
    - sns-subscription-server
    - unicode.hgrc

# While this file contains credentials, it needs to be world readable
# because pash is executed as a regular user, since it is what runs as
# the SSH command. We rely on pash's and Mercurial's security to not
# divulge its contents.
- name: install LDAP configuration for pash
  copy: src=ldap.json
        dest=/etc/mercurial/ldap.json
        owner=root
        group=root
        mode=0644

- name: Install entrypoint script
  copy: src=entrypoint.py dest=/entrypoint.py mode=0755

- name: virtualenv to run test-specific processes
  include: ../../../tasks/virtualenv3.yml
           python=/usr/bin/python3.6
           venv=/var/hg/venv_testing
           requirements=../roles/test-hg-ssh/files/requirements-testing.txt

- name: install unifyrepo testing config
  copy: src=unify-mozilla-unified-testing.ini dest=/etc/mercurial/unify-mozilla-unified.ini mode=0755

- name: setup notifications.ini testing config
  ini_file:
    path: /etc/mercurial/notifications.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: pulseconsumer, option: hosts, value: "hgssh:9092, hgweb0:9092, hgweb1:9092" }
    - { section: pulse, option: hostname, value: pulse }
    - { section: pulse, option: port, value: 5672 }
    - { section: pulse, option: ssl, value: false }

- name: setup Kafka hostports
  ini_file:
    path: /etc/mercurial/hgrc
    section: replicationproducer
    option: hosts
    value: "hgssh:9092, hgweb0:9092, hgweb1:9092"
  with_items:
    - { path: /etc/mercurial/hgrc, section: replicationproducer }
    - { path: /etc/mercurial/pushdataaggregator.ini, section: aggregator }

- name: install testing pushdataaggregator_groups file
  copy:
    dest: /repo/hg/pushdataaggregator_groups
    src: test_pushdataaggregator_groups
    owner: root
    group: root
    mode: 0644

- name: set privileged push hook repos to dummy values
  ini_file:
    dest: /etc/mercurial/hgrc
    section: mozilla
    option: lando_required_repo_list
    value: not-mozilla-central
    owner: hg
    group: hg

- name: set sentry_dns to empty value
  ini_file:
    dest: /etc/mercurial/hgrc
    section: mozilla
    option: sentry_dsn
    value: ""
    owner: hg
    group: hg
