#!/usr/bin/env python3.6
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import sys

repo = sys.argv[1]

with open(os.path.join(repo, '.hg', 'hgrc'), 'ab') as fh:
    fh.write(b'\n%include /etc/mercurial/hgrc-fastannotate\n')
