#!/venv/bin/python -u
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import subprocess
import sys
import urlparse

sys.path.insert(0, '/reviewboard/conf')
os.environ['DJANGO_SETTINGS_MODULE'] = 'reviewboard.settings'

site_url, autoland_url, bugzilla_url = sys.argv[1:]
site_url = urlparse.urlsplit(site_url)

# Define hostname.
from django.contrib.sites.models import Site as DjangoSite
site = DjangoSite.objects.get(pk=1)
site.domain = site_url.netloc
site.name = site_url.hostname
site.save()

# Define Autoland public URL.
from djblets.extensions.models import RegisteredExtension
mre = RegisteredExtension.objects.get(class_name='mozreview.extension.MozReviewExtension')
mre.settings['autoland_url'] = autoland_url.rstrip('/')
mre.save()

# Define Bugzilla URL.
from djblets.siteconfig.models import SiteConfiguration
sc = SiteConfiguration.objects.get_current()
sc.set('auth_bz_xmlrpc_url', '%s/xmlrpc.cgi' % bugzilla_url.rstrip('/'))
sc.save()

# Django caches the site settings in memory in each process
# and there doesn't appear to be an easy way to invalidate or
# change that setting. So, we kill the WSGI processes and rely on
subprocess.check_call(['/kill-wsgi-procs'])
